export const ERROR_CODES = [
  "AUTH_INVALID_CREDENTIALS",
  "AUTH_RATE_LIMITED",
  "AUTH_NO_SESSION",
  "AUTH_FORBIDDEN",
  "AUTH_USERNAME_TAKEN",
  "AUTH_RESET_TOKEN_INVALID",
  "AUTH_RESET_TOKEN_EXPIRED",
  "AUTH_RESET_TOKEN_USED",
  "OIDC_NOT_CONFIGURED",
  "OIDC_INVALID_STATE",
  "OIDC_INVALID_CODE",
  "OIDC_TOKEN_VERIFICATION_FAILED",
  "OIDC_DISCOVERY_FAILED",
  "VALIDATION_FAILED",
  "NOT_FOUND",
  "INTERNAL_ERROR",
] as const;

export type ErrorCode = typeof ERROR_CODES[number];
